### ISSUE TITLE
Create basics concept

### ISSUE THREAD

**Issue by lasarojc** [exercism/haskell#1001]
The haskell track does not have any concepts. Start with the basics one.

**Comment by pwadsworth** [comment]
I'll start working on that as a Christmas project. It will also help me solidify my own learning.

**Comment by BethanyG** [comment]
_you don **have to**, but there is the [`Lasgana`](https://github.com/exercism/docs/blob/main/building/tracks/stories/basics.lasagna.md) story that can be adapted..._

**Comment by pwadsworth** [comment]
Thanks @Bethany, I'll use that.
