### ISSUE TITLE
Data.Set failing to import in solution

### ISSUE THREAD

**Issue by mortal1** [exercism/haskell#1003]
When trying to use `Data.Set` in my solution to Pangram, using the online editor, I get the following compilation error
```
[1 of 2] Compiling Pangram

/mnt/exercism-iteration/src/Pangram.hs:9:1: error:
    Could not load module ‘Data.Set’
    It is a member of the hidden package ‘containers-0.6.2.1’.
    Perhaps you need to add ‘containers’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
9 | import qualified Data.Set as S
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

--  While building package pangram-2.0.0.12 (scroll up to its section to see the error) using:
      /opt/test-runner/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.4 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0 build lib:pangram test:test --ghc-options &quot;&quot;
    Process exited with code: ExitFailure 1
```

In the mentor notes for Pangram, it suggests a solution using `Data.Set` so I tried implementing it myself. It seems like it used to work but no longer does.

**Comment by hraftery** [comment]
FWIW, I had no such problems using the _offline_ editor a few weeks ago. The `dependencies:` section of `package.yaml` for this particular exercise contains `containers` by default.

**Comment by ErikSchierboom** [comment]
> I see, so it's probably the case that the online editor doesn't give the option of editing the package.yaml file, then?

It can though, that's entirely up to the track. For that to work, the `package.yaml` file needs to be added to the `files.solution` key in the exercise's `.meta/config.json` file.
