### ISSUE TITLE
"Palindrome Products" test does not time execution

### ISSUE THREAD

**Issue by hraftery** [exercism/haskell#1023]
Submitting a solution that passes the tests offline, but takes a long time to run, results in "YOUR TESTS TIMED OUT". This is despite the test suite locally reporting, say, "Finished in 0.0006 seconds".

Running the test suite locally does indeed exhibit a long pause, but prior to the test reports, at the point in the output indicated below:

```
$ stack test
palindrome-products-1.1.0.4: unregistering (local file changes: package.yaml palindrome-products.cabal)
palindrome-products> configure (lib + test)
Configuring palindrome-products-1.1.0.4...
palindrome-products> build (lib + test)
Preprocessing library for palindrome-products-1.1.0.4..
Building library for palindrome-products-1.1.0.4..
[1 of 2] Compiling Palindromes
[2 of 2] Compiling Paths_palindrome_products
Preprocessing test suite 'test' for palindrome-products-1.1.0.4..
Building test suite 'test' for palindrome-products-1.1.0.4..
[1 of 2] Compiling Main [Palindromes changed]
[2 of 2] Compiling Paths_palindrome_products
Linking .stack-work/dist/x86_64-osx/Cabal-3.2.1.0/build/test/test ...
palindrome-products> copy/register
Installing library in /Users/liteyear/Exercism/haskell/palindrome-products/.stack-work/install/x86_64-osx/d67bbd4c6b91cab47acba5c1822ab6f2841443cad8b8e5c86dbc1303257ef49b/8.10.7/lib/x86_64-osx-ghc-8.10.7/palindrome-products-1.1.0.4-L6G1WktRccE50uUjhs9DJT
Registering library for palindrome-products-1.1.0.4..
palindrome-products> test (suite: test)
                                 
                 <LONG PAUSE HERE>

palindromes from single digit factors
  smallestPalindrome
    value
    factors
  largestPalindrome
    value
    factors
<SNIP>
```

The issue is that the user gets no indication that the delay is in their code, let alone which particular cases trigger it. I wrongly suspected the infrastructure was at fault.

It turns out this behaviour is because of the nifty `case` statement in the `Tests.hs` file here: https://github.com/exercism/haskell/blob/d1d900d33ea60880d953cc40a782cd82cb34c890/exercises/practice/palindrome-products/test/Tests.hs#L21-L26

The `case` checks whether the tested function returns a Just or Nothing and provides an appropriate test. Alas, it appears this means that the function needs to be executed for all test cases before the test itself can be defined.

Removing the `case`, and defining only one type of test (non-ideal in the case of a Nothing result) restores the expected behaviour - tests start executing straight away without the pause, moving the pause to the test case which is actually slow, and including the actual execution time in the "Finished in" output at the end of the test.

The following will do to replace the lines referenced above:

```
              describe slDesc $ do
                let (value,factors) = fromMaybe (0,[]) result
                it "value"   $ value `shouldBe` expPal
                it "factors" $ normalize factors `shouldBe` expFac
```

`import Data.Maybe (fromMaybe)` also needs to be added to the import list.

**Comment by petertseng** [comment]
I agree that this is a problem but I think it's better solved without bogus value `(0, [])`. Instead, move the Just/Nothing into each element of the tuple. The following code will do. There may be ways to refactor it to get a similar result.

```haskell
              describe slDesc $ do
                let value = fmap fst result
                let factors = fmap snd result
                it "value"   $ value                  `shouldBe` Just expPal
                it "factors" $ fmap normalize factors `shouldBe` Just expFac
```

**Comment by petertseng** [comment]
EBWODP: better alignment in this code:

```haskell
+              describe slDesc $ do
                let value   = fmap fst result
                let factors = fmap (normalize . snd) result
                it "value"   $ value   `shouldBe` Just expPal
                it "factors" $ factors `shouldBe` Just expFac
```

**Comment by petertseng** [comment]
Not easy to see this one! Wonder whether any other exercises also have a similar problem.

The tests would have to be written in a specific incorrect way.

For example one might look at `dominoes` and think it's wrong because `shouldBeChain` matches on the result, but it's fine because it occurs within an `it`.

Wonder if there's a way to automatically detect it.

It's most likely to be a problem for exercises whose implementations might take a long time, so perhaps if there's no way to automatically detect it, at least those exercises can be manually inspected.

**Comment by hraftery** [comment]
Yes, had me looking in all the wrong places for a while. It occurred to me that it's a bit of a flaw in `hspec` - seems there's an implicit assumption that the test description can be evaluated lazily. So maybe `hspec` is the place to fix it. In other testing libraries I've seen "got hit" type tests that tell you whether a particular code path has been taken. I could imagine that `hspec` could check that nothing "got hit" until the `describe` has been sent to I/O. Seems like a pretty good pre-condition to assert, but lots of devil in the details. And I'm still a noob ;-)
