### ISSUE TITLE
README: Document the expected directory structure of a concept exercise

### ISSUE THREAD

**Issue by petertseng** [exercism/haskell#1029]
Our README covers how to add a practice exercise. Now that we have at least one concept exercise, we should make sure it explains how to add a concept exercise. Feel free to link to Exercism-wide documentation as appropriate, though there will be some Haskell-track-specific items such as the directory structure and expected files.

**Comment by pwadsworth** [comment]
I'll address this on my next PR.

**Comment by pwadsworth** [comment]
@petertseng I think this is fully covered in #1084. Are there any additional requirements?

**Comment by petertseng** [comment]
Should have used a word in https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue.
