### ISSUE TITLE
Exercise Bob does not make available a recommended library 

### ISSUE THREAD

**Issue by pwadsworth** [exercism/haskell#1033]
Instructions for exercise Bob recommends the use of Data.Text: "For more efficient handling of textual data, the Text type can be used. (...) Add - text to your list of dependencies in package.yaml."

Data.Text is not made available for the online tests, making the tests fail if the solution tries importing it. 

Fix: add Data.Text to the exercise package.yaml.

**Comment by ErikSchierboom** [comment]
We have an ongoing discussion about this in: https://github.com/exercism/haskell/issues/1006 Care to post your thoughts there?
