### ISSUE TITLE
Add Data.Map (containers-0.6.2.1) to common dependencies

### ISSUE THREAD

**Issue by artamonovkirill** [exercism/haskell#1041]
If my solution (e.g., the [Grade School](https://exercism.org/tracks/haskell/exercises/grade-school/solutions/KirillArtamonov)) imports `Data.Map`, the test runner fails with:
```
/mnt/exercism-iteration/src/School.hs:4:1: error:
    Could not load module 'Data.Map'
    It is a member of the hidden package 'containers-0.6.2.1'.
    Perhaps you need to add 'containers' to the build-depends in your .cabal file.
```

Given that `Data.Map` is the 3rd most popular import (see https://github.com/exercism/haskell/issues/1006), would be nice to have it imported by default.

**Comment by artamonovkirill** [comment]
@ErikSchierboom

**Comment by ErikSchierboom** [comment]
@petertseng Is this the same issue described in https://github.com/exercism/haskell/issues/1006? Or is `containers` a dependency we need to add to the test runner's precompiled dependencies list: https://github.com/exercism/haskell-test-runner/blob/main/pre-compiled/package.yaml#L11?

**Comment by artamonovkirill** [comment]
@petertseng submitting `package.yaml` works fine with the CLI, but not in the online editor.

@ErikSchierboom are there currently any tracks that allow editing multiple files in the online editor or that allow to add extra libraries in some other way?

**Comment by ErikSchierboom** [comment]
The C/C++ tracks have both a .h and a .c/.cpp file the student can edit. There is no special way to add extra libraries.

**Comment by artamonovkirill** [comment]
Should `package.yaml` be editable online for (some) Haskell exercises?

**Comment by ErikSchierboom** [comment]
Possibly, yes

**Comment by isaacvando** [comment]
Now that the online editor supports editing the `package.yaml` file (per #1080), I think it could be a good time to close this issue. 

It seems more consistent to me to not include `containers` in the `package.yaml` file. If I was new to the track and didn't know about adding dependencies to `package.yaml`, it would be quite frustrating that importing `Data.Map` worked for grade-school but none of the other problems that didn't have `containers` added already.

**Comment by artamonovkirill** [comment]
Thanks for the update and sorry for taking so long to reply.

I can edit `package.yaml` online, and specifying `containers` dependency without a version.

But adding a version constrain (`containers >= 0.6.3`) breaks the build:
```
No information from Hackage index, updating
Selected mirror https://hackage.haskell.org/
Downloading root
HttpExceptionRequest Request {
  host                 = "hackage.haskell.org"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept-Encoding",""),("User-Agent","Haskell pantry package")]
  path                 = "/root.json"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "hackage.haskell.org", service name: Just "443"): does not exist (Try again))
 ```
 
 If I remember correctly, the test runner does not have Internet access when running the tests.
 If so, how do I know which packages / versions available at the runtime?

**Comment by MatthijsBlom** [comment]
The exercises use a Stackage snapshot. `stack.yaml` specifies which one. It looks like this isn't visible in the web editor, but when you really need to know you can find it in the track repo: [example](https://github.com/exercism/haskell/blob/main/exercises/practice/hello-world/stack.yaml). (Likely all 18.14 right now.)

The versions included in a snapshot are listed [on Stackage](https://www.stackage.org/lts-18.14).

**Comment by artamonovkirill** [comment]
There's already a little comment explaining adding dependencies:
```
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.
```
Would it be too much information to add a disclaimer that just any version would not work? And/or a short explanation about Stackage, maybe with some links?

**Comment by MatthijsBlom** [comment]
```
# dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.
                # Do not specify version bounds!
                # Versions are derived from the Stackage snapshot.
                # You can find your snapshot in `stack.yaml`.
                # The package versions are listed on the corresponding
                # web page. Example:  www.stackage.org/lts-18.14
```

I feel this becomes a lot, fast. I'm fine with the `Do not specify version bounds!`, but less so with the rest. A complication is that `stack.yaml` is not visible from the web editor. Also, I'm not sure what happens when the snapshot is changed. I did this succesfully multiple times, but am not sure success is guaranteed.

&hellip;Maybe this file could be / is automatically generated (?), and the text could be shortened to

```
# Do not specify version bounds!
# The versions used in this exercise are listed here:  www.stackage.org/lts-18.14
```

**Comment by artamonovkirill** [comment]
Just something like 
```
# Do not specify version bounds!
# Versions are derived from the Stackage snapshot.
```
should be OK, I think. If the version of Stackage would be there - even better, not required.

But this discussion is probably outside of the scope of this ticket - I'll close this one and create a new one for the disclamer.

**Comment by artamonovkirill** [comment]
Created https://github.com/exercism/haskell/issues/1098
