### ISSUE TITLE
Haskell stack needs 2.5gb of space

### ISSUE THREAD

**Issue by bmacho** [exercism/haskell#1043]
Also it needs 5 gb of free space for installation.

I can't test my solutions without it. That's a bit extreme space requirement, just for checking if two values are equal.

Wouldn't it be possible and desirable to test only with ghc/ghci, without the need of the whole stack?

**Comment by ErikSchierboom** [comment]
@petertseng I've moved this to the haskell repo. Feel free to close this if you feel this is handled by the above mentioned issues.

**Comment by petertseng** [comment]
Yes, I confirm that the above two issues are the actions that should be taken in response to this issue.
