### ISSUE TITLE
CI fails with nightly build

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/haskell#1060]
Lately, CI has been failing with the nightly build: https://github.com/exercism/haskell/runs/5791854948?check_suite_focus=true

The error occurs in the step that tries to install `hlint`:

```shell
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for hlint-3.3.6:
    ghc-lib-parser-9.2.2.20220307 from stack configuration does not match ==9.0.*  (latest matching
                                  version is 9.0.2.20211226)
    ghc-lib-parser-ex-9.2.0.3 from stack configuration does not match >=9.0.0.4 && <9.0.1  (latest
                              matching version is 9.0.0.6)
needed since hlint is a build target.

Some different approaches to resolving this:

  * Set 'allow-newer: true'
    in /home/runner/.stack/config.yaml to ignore all version constraints and build anyway.

  * Recommended action: try adding the following to your extra-deps
    in /home/runner/.stack/global-project/stack.yaml:

- ghc-lib-parser-9.0.2.20211226@sha256:8b32bd5d2a8ee6bed6b6ea037fc0475841e2d0c46cb1bbfd2e4b5a934af5d574,10685
- ghc-lib-parser-ex-9.0.0.6@sha256:79ead389dbbdb178421cba35e9776d4d8feccf36d5d1f8fcc90441f8ec786cfe,3655

Plan construction failed.
```

@petertseng Thoughts?

**Comment by petertseng** [comment]
one thing I am slightly (but not terribly) worried about is the Haskell track makes some change to fix this, we forget about it, it gets fixed upstream, and then we have that change for no reason. If that is a valid worry, the track should take no action and instead wait for it to be fixed upstream.

**Comment by ErikSchierboom** [comment]
Sure. I don't have the required knowledge to make an educated guess on whether this is something temporary or not, but it sounds reasonable to just wait and see if this is fixed.

**Comment by petertseng** [comment]
https://github.com/exercism/haskell/actions/runs/2251615786

**Comment by ErikSchierboom** [comment]
Yay!

**Comment by petertseng** [comment]
The Haskell track took no specific action, and the issue resolved itself upstream
