### ISSUE TITLE
Allow editing of package.yaml in web editor by adding it to files.solution

### ISSUE THREAD

**Issue by petertseng** [exercism/haskell#1076]
To allow students to edit the package.yaml, for **each exercise**'s `.meta/config.json`, add `package.yaml` `files.solution`, such as:

```json
  "files": {
    "solution": [
      "src/Accumulate.hs",
      "package.yaml"
    ],    
    "test": [
      "test/Tests.hs"
    ],    
    "example": [
      ".meta/examples/success-standard/src/Accumulate.hs"
    ]     
  }, 
```

This applies to all exercises under `exercises/concept` and `exercises/practice`.

You should also add `package.yaml` to `files.solution` in https://github.com/exercism/haskell/blob/main/config.json, which can be of use when creating new exercises.

In your commit message please use a word from https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue to say that the commit closes these two issues

* https://github.com/exercism/haskell/issues/1003
* https://github.com/exercism/haskell/issues/1076 (this issue)

**Comment by isaacvando** [comment]
Is there any way to test changes like this locally? I looked but was not able to figure anything out.
