### ISSUE TITLE
Reference directory structure does not match current use.

### ISSUE THREAD

**Issue by pwadsworth** [exercism/haskell#1082]
The reference directory structure in [ \haskell\reference\implementing-a-concept-exercise.md](https://github.com/exercism/haskell/blob/main/reference/implementing-a-concept-exercise.md) does not match the one currently used in the Haskell track. 

eg. The reference shows `<STUB>/examplars/success-standard/` . The current structure is `<STUB>/.meta/examplar/`

Does the reference need to be updated or the structure changed?

**Comment by petertseng** [comment]
We have no choice but to change the documentation. We cannot move the exemplar out of .meta because we do not want to serve it to the students.
