### ISSUE TITLE
exercism cli not installing most recent version of project template

### ISSUE THREAD

**Issue by codeguru42** [exercism/haskell#1188]
When I run `exercism download --track=haskell --exercise=crypto-square` on MacOS with a M2 processor, I get a version of the project code that includes the following `stack.yaml`:

```
resolver: lts-18.14
```

Then running `stack build` gives an error because this project is using a version of GHC requires LLVM to compile for ARM processors and I don't have it installed. Manually changing the resolver to a newer version fixes the issue. But why did `exercism download` give me an old version of the project to begin with? I see that the version of `stack.yaml` on main has a newer resolver: https://github.com/exercism/haskell/blame/main/exercises/practice/crypto-square/stack.yaml.

**Comment by MatthijsBlom** [comment]
Might you have previously started this exercise? In that case there should be a notification on the web page that looks like this:

![image](https://github.com/exercism/haskell/assets/19817960/df5fe588-84aa-4cec-874f-69c6ef330359)

When you click on «_See what's changed&hellip;_» you can update the exercise, after which you can redownload.

If this was not the problem, please post on the forum.
