### ISSUE TITLE
travis: Initial building time near the limit of 50 minutes

### ISSUE THREAD

**Issue by rbasso** [exercism/haskell#568]
While trying to bump Stack's snapshot version in #566, we discovered that out initial building times are over 50 minutes, causing Travis to fail:

> The job exceeded the maximum time limit for jobs, and has been terminated.

The current situation is undesirable, because it effectively makes it impossible for us to test/approve new PRs.

We have two things to solve here:

- [x] Find a short-term solution so that we can go back to business ASAP. (#569)
- [ ] Rethink how we're doing our tests and write a more sustainable solution.

To deal with the immediate problem, I suggest us to, temporarily, do the following:

- Disable building the benchmarks, because `criterion` is a really heavy dependency and this has a low impact.
- ~~Disable building `hlint`, if disabling the benchmarks isn't enough.~~

**Comment by petertseng** [comment]
> Disable building the benchmarks, because `criterion` is a really heavy dependency and this has a low impact.

Let's try and see how it goes. Then consider:

* Moving benchmarks to their separate Travis job?
* Moving `hlint` to its separate Travis job?

**Comment by petertseng** [comment]
Regarding building time, while I would be interested in a change that only runs tests on changed exercises, I acknowledge that this doesn't solve the problem for a Stack resolver change, since in that case all exercises change.

**Comment by sshine** [comment]
The last 12 CI runs have had an average of 20 minutes, and the peak was 36 minutes.

The next time we will likely visit and measure build times is when migrating to GitHub Actions in #921.

So perhaps this issue has outlived its purpose of initially reducing build times.

If not, feel free to open it again.
