### ISSUE TITLE
maintainers: rbasso has left the building 

### ISSUE THREAD

**Issue by rbasso** [exercism/haskell#589]
I know that I'm not being very active here since May, and I don't know when/if I'll find the time to return to my duties as a maintainer.

While I would love to spend some time with Haskell and Exercism, the truth is that my current, non-IT-related, full-time job is killing my hobbies.

I may be able to take a look at the repository from time to time, but please don't count on me for anything. Feel free to remove me from the maintainers team when you think it is best.

Sorry for leaving you alone without notice, @petertseng, but I'm sure this track is in good hands!

Thank you for the opportunity of becoming a maintainer, @kytrinyx. It was a really great experience!

See you!
😄

**Comment by kytrinyx** [comment]
❤️ ❤️ ❤️ Thank you so much for all the work that you've put into the Haskell track. It needed it so sorely, and is so much better for it.

Want to submit a PR and stick an "alumnus" label on your entry in https://github.com/exercism/haskell/blob/master/config/maintainers.json? I'll remove you from the team, but you are (of course!) welcome back any time.

**Comment by Smarticles101** [comment]
Ooh! Seeing this remind me of a friend who likes to use haskell. I'm going to see if he's interested in contributing here :)

**Comment by rbasso** [comment]
> Want to submit a PR and stick an "alumnus" label on your entry in https://github.com/exercism/haskell/blob/master/config/maintainers.json?

That is the idea. I'll submit it as soon as I get the opportunity - no git in the computer I'm using now - unless someone does it first. 😁 

> I'll remove you from the team, but you are (of course!) welcome back any time.

😄

**Comment by petertseng** [comment]
Thank you for your work. It has been a pleasure to work with you. You will be missed.

I'll keep the lights on. I see that my time is limited these days, so I may not make many improvements to the track personally, but I'll keep things moving.

**Comment by petertseng** [comment]
Well, okay, I guess now I have to ask about this.

> > Want to submit a PR and stick an "alumnus" label on your entry in https://github.com/exercism/haskell/blob/master/config/maintainers.json?
>
> That is the idea. I'll submit it as soon as I get the opportunity - no git in the computer I'm using now - unless someone does it first.

So, I can tell you that if I am the one to do it, there will be no other track maintainer to review it, so I will not be able to merge it. If that means approvals should no longer be required and we agree, then we will want to change that.

**Comment by kytrinyx** [comment]
> If that means approvals should no longer be required and we agree, then we will want to change that.

Yeah, I think approvals probably shouldn't be required. Let me know if I should make the change.

**Comment by petertseng** [comment]
> > If that means approvals should no longer be required and we agree, then we will want to change that.
>
> Yeah, I think approvals probably shouldn't be required. Let me know if I should make the change.

As soon as I need to make a PR personally, I will need it to change... and I now have a PR that I need to make (bring READMEs in sync with problem-specifications) that I think I wouldn't ask some other contributor to do (don't want them to have to deal with the generator), so at this point I will ask for the change to be made.

It matches up with the proposal in https://github.com/exercism/discussions/issues/174 anyway.

**Comment by kytrinyx** [comment]
Done. Let me know if you need any other changes.
