### ISSUE TITLE
refactor robot-name; is it the right time to introduce IORef?

### ISSUE THREAD

**Issue by jonschoning** [exercism/haskell#590]
https://github.com/exercism/haskell/tree/master/exercises/robot-name … absolutely needs to be re-written, since the test-suite forces you to do lots of IO; IO could be introduced better/sooner in smaller bits.

Beginners don't know about `IORef` which this problems needs.

**Comment by unmanbearpig** [comment]
For me it was useful. I remember that I heard something about a few tools for mutable state in Haskell but I never used or researched any of them before doing this exercise. So I did some research and decided that IORef should work, and it did. I also haven't found it too hard for me.
On the other hand, I found that many exercises are redundant or very similar to each other, so I think it's good to have some variety and have students do some research, it makes it more fun, to me at least. Inspire students to learn more things about the language and the libraries. 
Although I agree that we probably shouldn't focus on IO, at least not in the beginner exercises.
That's just my experience, I might be a minority - that's at least my third time trying to learn Haskell after giving up on it multiple times in the past.

**Comment by jonschoning** [comment]
To re-phrase a little bit, what I thought was odd, was that something that _seemed_ like it shouldn't require IO (a simple record update, to update the robot name), was forced to require an IO-based solution.   The outcome I am trying to defend against is someone thinking record updates require IO by virtue of this exercise.  So the, for me, perhaps this is just a matter of characterizing why the IO is necessary and correct here.

**Comment by unmanbearpig** [comment]
Ah, I got what you mean, IO shouldn't be required for that task, I think you're right. 
Do you have any suggestions how to rewrite it?

**Comment by jonschoning** [comment]
Looking at the other ways languages have implemented this, perhaps IORef is the correct way to do this since I assume the exercise should have parity with other languages. Since I can't think of a better way, I suppose it's fine.
