### ISSUE TITLE
"Installing Haskell": Explicitly explain that Stack will install Haskell

### ISSUE THREAD

**Issue by HelgeStenstrom** [exercism/haskell#608]
The headline of http://exercism.io/languages/haskell/installation says that it's about installing Haskell, but it's really about installing Stack and HLint. As far as I can see.

Task:

Modify https://github.com/exercism/haskell/blob/master/docs/INSTALLATION.md to explain that Stack will install Haskell.

**Comment by NobbZ** [comment]
Stack will install an appropriate haskell when you run it the first time to compile a project.

**Comment by Average-user** [comment]
@NobbZ I was about to say something similar. But still, it wouldn't be bad to put a link to the [Haskell website](https://www.haskell.org/), just for completeness.

**Comment by NobbZ** [comment]
You are definitively right. I'd even say, the fact that stack will install haskell when it is needed in the correct version should be explained on the linked page.

**Comment by troglotit** [comment]
I'd make it clear that exercises use stack; as long as I'm right that you're not able to use Haskell platform/cabal on stack projects(with stack.yml), better to advice not use other installations, at least for exercism

**Comment by petertseng** [comment]
> as long as I'm right that you're not able to use Haskell platform/cabal on stack projects(with stack.yml)

My latest information is > 1 year out of date (it's https://github.com/exercism/haskell/issues/182#issuecomment-231537363). At the time, I had confirmed that it is still possible, by running `runghc -Wall -isrc test/Tests.hs`. I am currently unable to determine whether that is still true.

**Comment by dogweather** [comment]
Yes, and I believe that `ABOUT.md` should be updated to reflect this when it's being cleaned up in line with https://github.com/exercism/meta/issues/85. I.e., currently `ABOUT.md` only mentions cabal.

**Comment by petertseng** [comment]
I will edit the first comment to include the following task:

Modify https://github.com/exercism/haskell/blob/master/docs/INSTALLATION.md to explain that Stack will install Haskell.

**Comment by jeeger** [comment]
I've added a short section about the installation of GHC and checking it to the readme in PR #744. Lemme if there's changes necessary!
