### ISSUE TITLE
Exercise ordering: isbn-verifier and rail-fence-cipher

### ISSUE THREAD

**Issue by rbasso** [exercism/haskell#639]
`isbn-verifier` and `rail-fence-cipher` are way harder than `space-age`.

This seems to be causing a lot of people to quit early in the track. Take a look at [the numbers](http://www.exercism.io/stats/haskell).

Also, **it would be expected to see a big spike in the new exercises**, because of old-time users finishing just the new ones, but what we see the opposite there, so I guess we have a problem with the ordering.

In the past months, a lot of exercises where added, most of them with difficult *1* or *2*. Maybe it is time check the ordering to make the progression smoother.

I'm sorry but I'm just reporting the problem here. I'll probably not have the time to propose a new ordering soon.

**Comment by petertseng** [comment]
Prepare for discussion. Here are the exercises added in past 3 months (since 2017-09)

twelve-days
rail-fence-cipher
isbn-verifier
perfect-numbers
rotational-cipher
complex-numbers
diamond
isogram
collatz-conjecture

(Before that, was spiral-matrix added by rbasso in 2017-07)

**Comment by petertseng** [comment]
Okay, nobody wanted to discuss in the past 3 days. But I'd like to at least get rail-fence-cipher and isbn-verifier moved ASAP since it affects newcomers.

**Comment by petertseng** [comment]
I also decided to move run-length-encoding

**Comment by rbasso** [comment]
Thanks for doing all the work, @petertseng. 👍
