### ISSUE TITLE
palindrome-products: Use Maybe, returning Nothing when there is no palindrome in the given range

### ISSUE THREAD

**Issue by petertseng** [exercism/haskell#657]
Ever since https://github.com/exercism/problem-specifications/pull/894 was added, there are cases where there are no palindromes in range. We should add such cases, and have the tested function return `Nothing` in this case.

Tasks:

* Increment version number
  * Find the version number in https://github.com/exercism/haskell/blob/master/exercises/palindrome-products/package.yaml.
  * Make the first three components equal to the version in https://github.com/exercism/problem-specifications/blob/master/exercises/palindrome-products/canonical-data.json, and increment the fourth component by one.
  * For example, if package.yaml says 0.1.0.2 and canonical-data.json says 1.1.0, change to 1.1.0.3.
  * Reason: So that the Haskell track can record the fact that it is up-to-date with problem-specifications.
* Incorporate test cases:
  * Ensure that test cases in https://github.com/exercism/haskell/blob/master/exercises/palindrome-products/test/Tests.hs are equal to the new cases in https://github.com/exercism/problem-specifications/blob/master/exercises/palindrome-products/canonical-data.json.
  * This will certainly involve adding some cases
  * This may involve changing some existing ones.
  * Reason: It is good to have consistency among language tracks because interesting test cases are independent of language.
* Extend the test code:
  * Extend the test code in https://github.com/exercism/haskell/blob/master/exercises/palindrome-products/test/Tests.hs to be able to handle a function that returns a `Maybe`.
  * Reason: The new cases will add `Maybe`, so the code that runs the test cases needs to be able to handle that.
* Add `Maybe` to stubs:
  * Add `Maybe` to the function stubs in https://github.com/exercism/haskell/blob/master/exercises/palindrome-products/src/Palindromes.hs
  * (The CI will ensure that this was done correctly, so it's got your back in case you forget!)
  * Reason: These stubs are delivered to students when they start working on this exercise. We should ensure they see the correct types.
* Extend the example
  * Extend the example in https://github.com/exercism/haskell/blob/master/exercises/palindrome-products/examples/success-standard/src/Palindromes.hs to return `Nothing` in situations where there is no palindrome in the given range.
  * (The CI will ensure that this was done correctly, so it's got your back in case you forget!)
  * Reason: The example is used to ensure our test cases are solvable by at least one implementation.

**Comment by julienXX** [comment]
Hi @petertseng I'd like to try to submit a PR for this issue. Can I contact you if I have trouble?

**Comment by petertseng** [comment]
Thank you for your interest. Feel free to ask if you have trouble. You can ask here or on https://gitter.im/exercism/dev, your choice on which you prefer to use to ask.

**Comment by jeeger** [comment]
I've written a first implementation of this in PR #745.
