### ISSUE TITLE
Broken example in Haskell track's about page

### ISSUE THREAD

**Issue by freeboson** [exercism/haskell#693]
The `quicksort` example in https://exercism.io/my/tracks/haskell has some weird typos: `biggerSorted`'s definition is missing and the comprehension in `smallerSorted` is broken. The file in [`docs/ABOUT.md`](https://github.com/exercism/haskell/blob/master/docs/ABOUT.md) is correct, but that's not what's displayed on the webpage (see below).

<img width="427" alt="image" src="https://user-images.githubusercontent.com/1075679/42762241-1f0aaa88-8953-11e8-9d44-97854c6ff991.png">

**Comment by tejasbubane** [comment]
This is a markdown rendering issue on the website: https://github.com/exercism/exercism.io/issues/3970

**Comment by petertseng** [comment]
That deserves its own issue.

**Comment by sshine** [comment]
The markdown rendering issues in exercism/exercism#3970 were fixed 22 days ago, and the Quicksort snippet displays nicely. Removing it and improving on the snippet on the same page appears to be the purpose of #708, so this issue can be closed.

**Comment by petertseng** [comment]
Thank you for this report. I have now verified at https://exercism.io/tracks/haskell that the `quicksort` appears correct. This issue must now be closed.
