### ISSUE TITLE
nucleotide-count: Nucleotides have a misleading type

### ISSUE THREAD

**Issue by isovector** [exercism/haskell#694]
The function `nucleotideCounts :: String -> Either String (Map Char Int)` I'd suggest has the wrong type. Nucleotides are certainly an enum and not a `Char`. I worry the exercise as it stands today discourages people from thinking about data modeling and instead plays into a bias to use strings more often than they should be.

**Comment by petertseng** [comment]
I agree -- an enum would make sense so the type system can help make clear there are only four possible values at each position.

I would also take this opportunity to address what was said in https://github.com/exercism/haskell/issues/626#issuecomment-347012997

> While I think that enforcing invariables in the type system is a great idea, sometimes it is awkward to do that in Haskell. I don't think we should push all the exercises in this direction when it feels artificial in the language.
>
> About nucleotide-count, using length-parameterized types is idiomatic in Idris, but it is still considered type-hackery in Haskell, which is an advanced topic and would confuse students.

I still think there would be value in using a `data` for `nucleotide-count`; we don't have to do the Idris-style length-parameterisation.

I believe the files needed to edit to resolve this issue are the following:

* https://github.com/exercism/haskell/blob/master/exercises/nucleotide-count/test/Tests.hs
* https://github.com/exercism/haskell/blob/master/exercises/nucleotide-count/src/DNA.hs
* https://github.com/exercism/haskell/blob/master/exercises/nucleotide-count/examples/success-standard/src/DNA.hs

**Comment by sshine** [comment]
I agree. But if we use a

    data Nucleotide = A | C | G | T

then what's the point in having a `Map Nucleotide Int` when you could just have a

    data NucleotideCount = NC { _a :: Int, _c :: Int, _g :: Int, _t :: Int }

but then you wouldn't need the `Nucleotide` data type if the original input is a `String`.

Perhaps one should keep the `Map Nucleotide Int` since that adds complexity.

**Comment by sshine** [comment]
Should the tests keep asserting that the map contains all four nucleotides when a nucleotide occurred zero times?

**Comment by isovector** [comment]
@sshine I personally wouldn't let the `NucleotideCount` described above through in a real code review---it doesn't compose well with the ecosystem. Eg, writing `Nucelotide -> NucelotideCount -> Int` requires a pattern match that the compiler won't help you write correctly. When in doubt, use the definitions that are the hardest to get wrong.

**Comment by isovector** [comment]
@sshine nope, #714 looks great to me!
