### ISSUE TITLE
Fix getting started instructions for haskell

### ISSUE THREAD

**Issue by jackhughesweb** [exercism/haskell#704]
Some exercise README templates contain links to pages which no longer exist in v2 Exercism.

For example, C++'s README template had a link to /languages/cpp for instructions on running tests. The correct URLs to use can be found in the 'Still stuck?' sidebar of exercise pages on the live site. You'll need to join the track and go to the first exercise to see them.

Please update any broken links in the 'config/exercise_readme.go.tmpl' file, and run 'configlet generate .' to generate new exercise READMEs with the fixes.

Instructions for generating READMEs with configlet can be found at:
https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md#generating-a-readme

Instructions for installing configlet can be found at:
https://github.com/exercism/docs/blob/bc29a1884da6c401de6f3f211d03aabe53894318/language-tracks/launch/first-exercise.md#the-configlet-tool

Tracking exercism/exercism.io#4102

**Comment by petertseng** [comment]
For the Haskell track, a person who wants to fix this would want to change the link to http://exercism.io/languages/haskell. Note the use in context:

`For installation and learning resources, refer to the [exercism help page](http://exercism.io/languages/haskell).`

The current situation is that that link redirects to https://exercism.io/my/tracks/haskell. This page does provide the installation and learning resources - they are linked under the `Guides` section.

The person who would fix this might take one of several different approach:

* Keep the link the same, but explicitly say that the guides are under the `Guides` section.
* Change the link to https://exercism.io/my/tracks/haskell , but explicitly say that the guides are under the `Guides` section.
* Link directly to the specific guides being referenced in the sentence (1. installation 2. learning resources)
* Decide that it is good enough as is, and recommend that this issue be closed with no changes.
* Your suggestion here

**Comment by petertseng** [comment]
EBWODP:

> would want to change the link which currently points http://exercism.io/languages/haskell. 

Sentence unclear. Does the instructions mean you want to change the link  **from** X **to** http://exercism.io/languages/haskell ? No, instead it should be written this way for clarity:

might want to change the link **which currently points to** http://exercism.io/languages/haskell

**Comment by petertseng** [comment]
EBWODP:

> would want to change the link to http://exercism.io/languages/haskell. 

Sentence unclear. Does the instructions mean you want to change the link  **from** X **to** http://exercism.io/languages/haskell ? No, instead it should be written this way for clarity:

might want to change the link **which currently points to** http://exercism.io/languages/haskell

**Comment by jackhughesweb** [comment]
The purpose of this issue is to fix any old links from v1, such as:
https://github.com/exercism/haskell/blob/d51c53cbeb7ce24fe6a70bc9e03f91c962d65949/config/exercise_readme.go.tmpl#L11

Tracks previously had links in a sidebar to help pages, but this sidebar no longer exists in v2. 

Help pages can be accessed on the right hand side of exercise pages (and also at the bottom of https://exercism.io/tracks/haskell/learning) - could you change the line above to link to one (or more) of the new help page locations, and regenerate the config files with `configlet generate .`?

**Comment by petertseng** [comment]
Thank you for the new instructions. With the new instructions, the issue can now be reopened.
