### ISSUE TITLE
roman-numerals tests

### ISSUE THREAD

**Issue by Average-user** [exercism/haskell#705]
I think we should add some test that returns Nothing. Since otherwise I don't see the point of using ```Maybe```

https://github.com/exercism/haskell/blob/master/exercises/roman-numerals/test/Tests.hs

**Comment by petertseng** [comment]
This is a duplicate of https://github.com/exercism/haskell/issues/460 , but I promise to consider new viewpoints equally as old viewpoints.

**Comment by Average-user** [comment]
Ohh. My bad
