### ISSUE TITLE
Error counting the remaining number of unlocked exercises

### ISSUE THREAD

**Issue by Scientifica96** [exercism/haskell#712]
I just completed the core exercises of the Haskell track (I really enjoyed it; I thank all contributors). Here's the message I get:

![2018-08-31_091258](https://user-images.githubusercontent.com/24757417/44901016-23f92000-acfe-11e8-8974-cc870c1093e0.png)

However, there are only 78 exercises left:

![2018-08-31_091430](https://user-images.githubusercontent.com/24757417/44901072-4b4fed00-acfe-11e8-84c4-83076a5314fe.png)

**Comment by petertseng** [comment]
Noting the difference of five. Now, five is an interesting number. In https://github.com/exercism/haskell/blob/master/config.json , it is the number of *deprecated* exercises. That means it would be worth opening an issue in https://github.com/exercism/exercism about that. Tell them that the number of exercises in the "You have N unlocked side exercises that you have not yet completed" includes deprecated exercises, when it should not. (or maybe it's the other way around, I don't know) Please do (then close this issue, this issue can only serve as a reminder to open an issue in  https://github.com/exercism/exercism )

**Comment by Scientifica96** [comment]
Great, you found the origin of the error. I did as you said.
