### ISSUE TITLE
Robot Name Exercise - Enforcing Unique Name

### ISSUE THREAD

**Issue by zhenengxie** [exercism/haskell#725]
Currently the readme for the "Robot Name" exercise says:

> The names must be random: they should not follow a predictable sequence. Random names means a risk of collisions. Your solution must ensure that every existing robot has a unique name.

All the solutions I've seen, including the example solution, don't actually handle collisions. Practically speaking, the tests will be passed since the chance of collisions is so low. However I propose to do one of the following:

- change the readme to say you don't have to handle collisions
- rework the exercise with the State monad or StateT monad transformer

**Comment by zhenengxie** [comment]
Yes, sorry I missed that solution. However as acknowledged by the [Haskell wiki](https://wiki.haskell.org/Top_level_mutable_state#Proposal_2:_Top-level_.3C-) the "unsafePerformIO" hack is not really best practices. I feel the StateT monad transformer would be more idiomatic code and makes the state explicit. I've submitted a pull request that modifies the exercise to use it, but can't seem to get it to pass the tests.

**Comment by ajkavanagh** [comment]
I don't disagree with hack being a problem; with the current function signatures it was the only way to satisfy the problem statement.  An alternative will have to be to change the function signature(s) so that state can be passed back and forth. A StateT would handle that.

My solution even says:

```haskell
-- horrible hack to get a global variable, but it seems to be the only way!
robotNames :: IORef [String]
{-# NOINLINE robotNames #-}
robotNames = unsafePerformIO (newIORef [])
```

**Comment by petertseng** [comment]
> Practically speaking, the tests will be passed since the chance of collisions is so low

Should the tests contain a more rigourous check for collisions?
