### ISSUE TITLE
beer-song, food-chain, house: Re-evaluate whether to provide a working solution already

### ISSUE THREAD

**Issue by petertseng** [exercism/haskell#764]
As ratified in https://github.com/exercism/haskell/issues/301, we chose to provide a working solution to beer-song, food-chain, house. One of the reasons was:

> we could take the boring part out of some of them

This was somewhat important because in a linear track, students will inevitably* come across this exercise.

*: Not true if the student just decided to fetch exercises out of order, but I can make no claims about what proportion of students did so.

Now that the track is structured as a tree and none of these three exercises are core, the times have changed, but the question is whether they have changed enough to warrant a change here.

the alternative would be to do the same as we do in all other exercises, where we just say `error "You need to implement this function"`

For consideration, the current stubs we provide:

* https://github.com/exercism/haskell/blob/master/exercises/beer-song/src/Beer.hs
* https://github.com/exercism/haskell/blob/master/exercises/food-chain/src/FoodChain.hs
* https://github.com/exercism/haskell/blob/master/exercises/house/src/House.hs

**Comment by petertseng** [comment]
My opinion will be in this comment. If you don't want to be influenced by it, avert your eyes.

What if we provide no implementation, but a student wants to approach this as a refactoring exercise? then it is a chore to add the implementation that simply embeds the entire target string, though not a particularly difficult chore.

What if we provide the current implementation (including the entire target string) but a student wants to implement from scratch? Easy, just delete the existing implementation entirely.

To what extent does the choice made in this repo influence student actions? Maybe if the student is not aware of the choice, it is a weakness. If it's desired to address this weakness, there's the possibility of adding "you can just delete the entire thing if you want" to https://github.com/exercism/haskell/blob/master/exercises/beer-song/.meta/hints.md (and same for house and food-chain). Of course, note that the instructions in the repo of course ultimately have no power to dictate students' actions, and we may not be able to tell via the submitted solutions which process a student has taken.

I have not determined any reason why things should change.

If there are no further reasons to change presented within a week, this issue should be closed. It may be reopened when a reason is found.

**Comment by petertseng** [comment]
My specified period for discussion has passed without others' comments, so I will close this issue for now. However, I hope it would have gone without saying that even though I close this issue, it's always open for discussion in the future!

**Comment by sshine** [comment]
I'm sorry that I missed your window. I'd like more refactoring exercises on the Haskell track, and I've been working on `tree-building`, since it turns out that I can create really ugly solutions for that exercise!

I'd like to give this some thought. Until then, I think they're fine.
