### ISSUE TITLE
Shouldn't all exercises have `ghc-options: -Wall` in their package.yaml?

### ISSUE THREAD

**Issue by sshine** [exercism/haskell#769]
In `Space Age` I argue in my mentor feedback that one benefit of writing a total function,

    orbitalPeriod :: Planet -> Float
    orbitalPeriod Mercury = ...
    orbitalPeriod Venus = ...
    ...

is that GHC can warn you in case of missing or duplicate cases, and that this is useful when extending data types over time. But if you add a planet and forget to extend `orbitalPeriod`, `stack test` and `stack build` will not, actually, show this warning.

Which made me think, why don't we ad `ghc-options: -Wall` to package.yaml of all exercises?

**Comment by petertseng** [comment]
Yes, not only is this a good idea on its own merits, the history supports it as well because https://github.com/exercism/exercism/pull/804 added `-Wall` to the then-instructions. It seems that was lost on the move to Stack.

**Comment by sshine** [comment]
I've removed `ghc-options: -Wall` from all example package.yaml. Before the amend:

    $ git diff-tree --no-commit-id --name-only -r HEAD | wc -l
    201

    $ git diff-tree --no-commit-id --name-only -r HEAD | grep examples | wc -l
    105

After the amend:

    $ git diff-tree --no-commit-id --name-only -r HEAD | wc -l
    96

    $ git diff-tree --no-commit-id --name-only -r HEAD | grep examples | wc -l
    0

As 96 + 105 = 201, it seems that no other files were affected.

*(Actually, I did accidentally commit a rogue file and found it by doing this test. Hooray!)*
