### ISSUE TITLE
Use `Data.Text` when appropriate

### ISSUE THREAD

**Issue by sshine** [exercism/haskell#780]
- [x] List currently implemented exercises that rely heavily on `String`.
- [x] ~~Consider extending their test suites so they're compatible with `Data.Text`.~~
- [x] ~~Consider moving them so they're follow-up exercises to Bob.~~
- [x] ~~Consider if any of them may be good as a first pure `Data.Text` exercise.~~

**Updated:**
- [x] List currently implemented exercises where the test suite can support both `String` and `Text`

**Comment by sshine** [comment]
Exercises with `strings` in topics:

- `hello-world` (core), `bob` (core), `pangram` (core), `acronym`, `isogram`, `diamond`, `etl`, `raindrops`, `twelve-days`, `run-length-encoding`, `anagram`, `series`, `atbash-cipher`, `word-count`, `luhn`, `ocr-numbers`, `rotational-cipher`, `parallel-letters-frequency`, `pig-latin`, `rail-fence-cipher`.

**Comment by sshine** [comment]
Links that may be useful as hints for working with `Data.Text`:

- https://mmhaskell.com/blog/2017/5/15/untangling-haskells-strings (bit poor styling)
- https://hackage.haskell.org/package/text-1.2.3.1/docs/Data-Text.html (bit technical)
- http://blog.ezyang.com/2010/08/strings-in-haskell/ (bit old)
- https://haskell-lang.org/tutorial/string-types (nice! excellent in fact!)

**Comment by sshine** [comment]
I think we should either

1. `bob`: Add a comment in README that encourages `Text`.
2. `bob`: Switch entirely to `Text` just like #785 does to `pangram`.

The choice comes down to whether we should teach that there is a difference by first letting the student use the default, sub-optimal choice, and then progress to use a better, but more involved choice (since it depends on qualified imports and `OverloadedStrings`). Or if we should make that choice for them.

For some reason I find this decision very difficult. @reactormonk thinks we should kill `String`.

I agree that this is the end goal. But while Prelude uses it, there will be confusion.

**Comment by reactormonk** [comment]
I'd argue that we should add a disclaimer that `Prelude` is old, and never build for production use, but rather teaching purposes. And maybe suggest one of our own, we could have a small list of curated ones.

**Comment by sshine** [comment]
Since we're a teaching site is then Prelude should be the right choice. But since we also want to teach of choices beyond Prelude, perhaps custom preludes can be a subject later in the core track?

I don't know if I'm comfortable with switching *entirely* to a custom prelude that is not addressed in mainstream learning material.

If you create an issue for this, we can discuss where and which custom preludes to consider!

**Comment by sshine** [comment]
Quoting @Frerich on Slack:

> In fact, an exercise which asks to port an existing program suffering from the deficiencies of `String` (e.g. inefficiency) to `Text` might be fun. :-)

Excellent idea! I'm saving this idea here until a little later.

**Comment by sshine** [comment]
Exercises that work with both `String` and `Text`:
- [x] Bob in #760
- [x] Pangram in #788
- [ ] Update README hints

**Comment by sshine** [comment]
`pig-latin` was made compatible with `Data.Text` in #805.

**Comment by sshine** [comment]
Making this issue executable, I would like to make its current goal:

- [ ] To make the test suite compatible with `Data.Text` whenever possible (checklist below). This has happened for a number of exercises already.
- [ ] If applicable, convert some of these to `Data.Text`-only exercises and make them unlock by `bob`, which is currently the first core exercise where it is encouraged to try out `Data.Text`. It would be neat to have a side exercise after it that demanded it.

- [ ] ~~`hello-world`~~ (core); it is too early in the track.
- [x] `bob` (core)
- [x] `pangram` (core)
- [ ], `acronym`
- [ ] `isogram`
- [ ] `diamond`
- [ ] `etl`
- [ ] `raindrops`
- [ ] `twelve-days`
- [ ] `run-length-encoding`
- [ ] `anagram`
- [ ] `series`
- [ ] `atbash-cipher`
- [ ] `word-count`
- [ ] `luhn`
- [ ] `ocr-numbers`
- [ ] `rotational-cipher`
- [ ] `parallel-letters-frequency`
- [x] `pig-latin`
- [ ] `rail-fence-cipher`

**Comment by sshine** [comment]
I'm closing this issue and opening another more tidy one in expectation of Hacktoberfest.
