### ISSUE TITLE
Make `fail-*` examples not show up in red in Travis logs

### ISSUE THREAD

**Issue by sshine** [exercism/haskell#783]
When inspecting Travis CI logs, such as [this one](https://travis-ci.org/exercism/haskell/jobs/459782563#L560), the first red text that pops up relates to `exercises/accumulate/examples/fail-reverse`, which is a "fail example".

It's supposed to fail, but the red text in the Travis logs makes it pop up as something went wrong when it failed successfully.

We'd like to get rid of these red log messages so that scrolling the Travis log for actual errors doesn't flash these false negatives.

You can discuss any potential solution in this issue before submitting a PR if you're unsure that the approach is an example of good practice. (Exactly what is good practice here is uncertain to me; it could be that negative examples should be executed differently, or it could just be a shellscript hack that remaps ANSI color codes.)

- [x] Document how these negative examples are used for something. See [this section](https://github.com/exercism/haskell#example-solution).
- [ ] Suppress the red color and/or move negative examples to some other form.

**Edit:** Updated to clarify the remaining scope of this issue.

**Comment by petertseng** [comment]
Excellent!

I have kicked off the first item with a PR.

**Comment by sshine** [comment]
This problem no longer applies since #930 migrated to GitHub Actions which does not color its log.
