### ISSUE TITLE
Exercise-specific sections in READMEs for exercises

### ISSUE THREAD

**Issue by sshine** [exercism/haskell#787]
In #629 we inherited `bin/ensure-readmes-are-updated.sh` from the Rust track. :tada:

This prevents me from adding track-specific sections in the READMEs of particular exercises. For example, in #782 I'd like to add a section that links to teaching material on QuickCheck generators. And in #785 I'd like the same but for Data.Text. And come to think of it, I might like for this to be a general style in the core track: "This is where you go to read about X, which you'll need..."

Is there a policy against having an exercise-specific section for some exercises?

If not, perhaps we could complicate `bin/ensure-readmes-are-updated.sh` and check that the README is the concatenation of a) the description from problem-specifications, b) an optional section that always has the same header, but which of its content may be exercise-specific, and c) the track-specific portion.

If so, is there a discussion of the pros and cons? Perhaps on the Rust track from where this consistency check was inherited?

**Comment by petertseng** [comment]
> Is there a policy against having an exercise-specific section for some exercises?

There is no such policy.

`ls exercises/*/.meta/hints.md` for all the exercise-specific sections

**Comment by petertseng** [comment]
> > Is there a policy against having an exercise-specific section for some exercises?
>
> There is no such policy.

https://github.com/exercism/configlet#generate

**Comment by sshine** [comment]
Ok, thanks!
