### ISSUE TITLE
Re-adjust and limit difficulties for exercises?

### ISSUE THREAD

**Issue by sshine** [exercism/haskell#793]
In exercism/rust#460, four difficulties were picked: 1, 4, 7 and 10. I also believe that choosing between four difficulties results in a clearer cut, and I think the Haskell track should adhere to the same four categories. Subsequently we can adopt the CI hooks that verify difficulties from exercism/rust#503; as for the assertion that exercises are sorted by difficulty, await a final decision in #790.

**Comment by petertseng** [comment]
We might even consider only using distinctions the site considers significant.

https://github.com/exercism/website/blob/49450d71253cfbbb49ad7c4660ad74e060a315dc/app/controllers/my/side_exercises_controller.rb#L12-L18

https://github.com/exercism/website/blob/49450d71253cfbbb49ad7c4660ad74e060a315dc/app/helpers/exercise_helper.rb#L17-L23

In other words, we might select just one from each of the three categories. Perhaps 1, 5, 10, for example. Having a track-level distinction between 4 and 7 in our JSON file would only be necessary if we wanted to use it for some purpose that we discuss in this issue.

**Comment by sshine** [comment]
Good point!

For now I only really care about the "Easy" .. "Hard" labels. I intend to propose a restructure of the core track following a method that @F3PiX is heading once other tracks have gone through this; asserting difficulties in other granularity than 1-5-10 or 1-4-7-10 may apply then, so I'll wait a little.

**Comment by sshine** [comment]
I am closing this issue for now, and it can be returned to later.
