### ISSUE TITLE
Restructure Haskell core track

### ISSUE THREAD

**Issue by sshine** [exercism/haskell#798]
In an effort to restructure the Haskell core track I have followed @F3PiX'es Track Tool in its current incarnation. Step 1 took me through the current core track and yielded the initial proposal listed below.

- [x] Update `config.json` to reflect this via draft PR #800
- [x] Discuss these suggestions

---

- Switch "Bob" and "Pangram".

  They're both about handling textual data.

  Pangram has fewer gotchas, is quicker done, has more alternative solutions, and doesn't lend itself as well to `Data.Text`. (See #795.) Bob often involves more refactoring, has more learning objectives and has the extra "You could do it with `Data.Text`, too!" part.

  This way people don't try to solve Pangram with `Data.Text` which is possible but not ideal without [mono-traversable](https://hackage.haskell.org/package/mono-traversable), and they get an exercise more under their belt before being thrown into a lot of refactoring.

- Switch "Nucleotide Count" and "Sum of Multiples".

  Eventually I think we should delete "Sum of Multiples" and "Grains" (see #761).

  But since the Track Tool does not address removal yet, I want to make "Nucleotide Count" come immediately after "RNA Transcription", since they're both thematically related *and* Nucleotide Count uses `Either` while RNA Transcription uses `Maybe` for monadic error handling, so they practice the same thing in progressive difficulty.

---

The proposed track reordering looks like:

1. hello-world
2. leap
3. space-age
4. **pangram**
5. **bob**
6. collatz-conjecture
7. rna-transcription
8. **nucleotide-count**
9. *sum-of-multiples*
10. *grains*

**Comment by sshine** [comment]
Related:

- #192: discussion: Making the Haskell track more interesting for beginners

  Perhaps we can get an updated graph similar to this one.

- #194: discussion: Making the Haskell track more idiomatic

**Comment by petertseng** [comment]
I don't know what this Track Tool is or what steps comprise it, so it doesn't appear possible to evaluate whether the proposals meet any of its stated goals.

However, each proposal has been justified standalone and can be evaluated independently of knowledge of this Track Tool. I encourage that future proposals should continue to be justified in such a manner!

I agree with introducing `Maybe` before `Either`. This seems like a logical progression. I suspect (but don't have data to support) that other projects that educate also order them in this order.

I had to think a lot harder about pangram vs bob but I've come to agree. Both ask "is property P true of text T?" but pangram has only one P, where Bob has multiple (and not all mutually exclusive).

**Comment by sshine** [comment]
> I don't know what this Track Tool is or what steps comprise it, so it doesn't appear possible to evaluate whether the proposals meet any of its stated goals.

I've added the following description to the first commit message:

> As part of [The Track Anatomy Project](https://exercism.io/blog/track-anatomy-project), the Haskell core track is restructured in exercism#798 using @F3PiX'es multi-stage framework referred to as "The Track Tool".
>
> Since The Track Tool is still under development, it isn't documented yet. But the execution of the first step can be viewed for other languages, e.g. exercism/javascript#590.

And I also don't know exactly what this Track Tool is or what all its steps are.

But the first step is to reorder existing exercises and remove any "mathy" ones.

I've not removed any "mathy" ones; there's only `leap` and `collatz-conjecture`. They're not difficult by the standard of our current core track, and I don't think their degree of "mathiness" discourages the average Haskell learner. Surely it can get too "mathy", like `nth-prime`.

> I agree with introducing `Maybe` before `Either`. This seems like a logical progression. [...]

The right order was already there.

Having them in straight succession is perhaps better.

My main motivation was to group them by learning goal.

I don't know if this is optimal in later steps of The Track Tool; I supposed that I could always propose to add other exercises in between them if there were any good reasons to do so. For example, another more dominant learning goal.

> I had to think a lot harder about pangram vs bob but I've come to agree. Both ask "is property P true of text T?" but pangram has only one P, where Bob has multiple (and not all mutually exclusive).

That's a good way to put it.

**Comment by F3PiX** [comment]
As a side note:
> I don't know if this is optimal in later steps of The Track Tool; I supposed that I could always propose to add other exercises in between them if there were any good reasons to do so. For example, another more dominant learning goal.

That's correct. This first Round is a quick fix for the most obvious obstructions. Next rounds go from coarse to fine, and from easier to more advanced exercises.
More info on the Track Anatomy Project coming soon!

**Comment by petertseng** [comment]
> > I agree with introducing Maybe before Either. This seems like a logical progression. [...]
>
> The right order was already there.
> 
> Having them in straight succession is perhaps better.
> 
> My main motivation was to group them by learning goal.

Yes, it appears I misunderstood because of misreading the exercises that are being swapped vs the exercises mentioned in the rationale. (Without specific reference to exercises, A and B got swapped, and the rationale mentioning A and C). Therefore it wasn't possible to judge my position on the change, since my rationale targeted an incorrect premise.

So my actual evaluation on that change:

I think I'd be okay either way, so let's indeed go with the general principle of putting exercises with similar goals together.

**Comment by sshine** [comment]
Closing this issue as the effort described in it has played out.
