### ISSUE TITLE
Issues with rna-transcription

### ISSUE THREAD

**Issue by zuzia-kru** [exercism/haskell#801]
Hello,
I've been doing the 'rna-transcription' exercise and I think that the tests are not consistent. It seems that when given String is not a proper DNA the programme should return 'X' but one of the test says that given 'U' the programme should return 'X' (even though the testcase is called 'invalid input').

I had a look at the example solution and it fails the test with the following error:

```
  src/DNA.hs:7:5: 
  1) toRNA correctly handles invalid input (RNA instead of DNA)
       uncaught exception: PatternMatchFail
       src/DNA.hs:(7,5)-(10,28): Non-exhaustive patterns in function fromDNA
```

**Comment by NobbZ** [comment]
You are expected to return `Left invalidChar`, Not `'X'` literally.

**Comment by sshine** [comment]
Yes, it is `Left` of whatever character that doesn't represent a valid DNA nucleotide.

The negative test,

        , Case { description = "correctly handles invalid input (RNA instead of DNA)"
               , dna         = "U"
               , expected    = Left 'U'
               }

takes as input `"U"`, even though `'U'` is a valid RNA nucleotide, but not a valid DNA nucleotide.

So ``toDNA "U" `shouldBe` Left 'U'`` and ``toDNA "ACGTQ" `shouldBe` Left 'Q'``.

**Comment by zuzia-kru** [comment]
Thanks for the answers, I understand now.
For what it's worth I'm not sure that this is easy to deduce from the description of an exercise. I guess that a sentence like "Given invalid output your programme should return the first invalid Char." would be very helpful :)

**Comment by sshine** [comment]
@zuzia-kru: I agree, and @b-mehta does, too. :-)

We're a few git squashes from adding that.

Thanks for paying attention to the flow of the track.
