### ISSUE TITLE
"Require branches to be up to date before merging" - discuss and (if appropriate) request it be turned off

### ISSUE THREAD

**Issue by petertseng** [exercism/haskell#806]
**Current state of affairs**: The "Require branches to be up to date before merging" is enabled for this repository. An admin of the repository (I am not) will be able to see this is true, from https://github.com/exercism/haskell/settings/branches

**I allege** that this requirement causes friction:

* If multiple PRs are in flight, and we want to merge them all, we are required to: merge, rebase, wait for Travis CI of 5 minutes, merge, rebase, wait for Travis CI, etc.
* If a contributor so happens to branch off of master at any commit other than the current one, the maintainers or contributors must take action.
* I provide https://github.com/exercism/haskell/pull/802 as a recent example.

Hence, this issue is my **proposal that we might like to disable that requirement**.
I invite interested parties to comment on this proposal.
If there is agreement, we should ask one person who is an admin of this repo (so, picking one person among @ihid and @kytrinyx) to disable that setting.

Also note that if either of them indicates that this setting is **non-negotiable**, we need not discuss and should save ourselves the effort of discussing.
Therefore, I request a **quick notification if this setting is non-negotiable**.

The reasons in support of the proposal are my allegations of friction, as seen above.

The reasons in opposition of the proposal are that this setting is to **ensure safety**.

Every change that is merged to master will go live on the website in short order. Therefore, the maintainers should take appropriate care about such changes. One of the purposes of Travis CI is to check, in some automated fashion, that we don't break the website.

The particular setting "Require branches to be up to date before merging" protects against the case where two changes:

* Branch off of master at the same point
* Do *not* have a merge conflict in the `git` sense of that word (`git` is willing to merge the two changes together)
* Individually pass Travis CI (and presumably will not break the website, presumption A)
* Combined will break the website (presumably would not pass Travis CI, presumption B)

Call this a *logical conflict* (as opposed to the above-mentioned *merge conflict*).
"Require branches to be up to date before merging" will allow us to detect this sort of conflict (assuming presumption B holds), while disabling it will potentially allow it to slip by unnoticed and break the website.

Evaluation of this proposal depends on the probabilities and importances we assign to the above factors.

You may find the discusson of this setting in https://github.com/exercism/discussions/issues/174 and its continuation https://github.com/exercism/exercism/issues/4129.

**Comment by sshine** [comment]
> Therefore, I request a **quick notification if this setting is non-negotiable.**

@ihid or @kytrinyx: Could one of you provide this quick notification?

I'm also in favor of turning off this feature for the Haskell track.

We already have quite a lot of safe-guarding policies wrt. the format of pull requests.

I suppose conflicts might most likely arise when changing things that affect the entire track, such as `config.json` or `bin/`, or if two pull requests address the same exercise. But the majority of concurrent pull requests are entirely conflict-free. I suppose that one could also require this conditionally based on whether `config.json` was affected.

Merging multiple pull requests from multiple hours in short succession is simply not possible with people not being available and not everyone having enabled maintainers to push to their feature branches. (I've witnessed this merging 3-4 things today.)

**Comment by iHiD** [comment]
I defer to @kytrinyx for this issue :)

**Comment by kytrinyx** [comment]
I think this is totally fine. I'll turn it off now.

**Comment by kytrinyx** [comment]
Done.

**Comment by petertseng** [comment]
Thanks a lot!
