### ISSUE TITLE
`stack test` fails in hello world project

### ISSUE THREAD

**Issue by Datamance** [exercism/haskell#845]
after a fresh install of Exercism (just learned about it today - what a neat idea!), and running `stack test` in the `hello-world` directory, I get this long error about clang failing to link some dependencies:

```
Linking /Users/<_______>/.stack/setup-exe-cache/x86_64-osx/tmp-Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3 ...
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
ld64.lld: warning: ignoring unknown argument: --gc-sections
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -u
ld64.lld: warning: ignoring unknown argument: -search_paths_first
ld64.lld: warning: -sdk_version is required when emitting min version load command.  Setting sdk version to match provided min version
Cannot open /Users/<_______>/.stack/setup-exe-src/setup-mPHDZzAJ.o: bad relocation (Invalid pointer diff) in section __TEXT/__text (r1_address=238, r1_type=5, r1_extern=1, r1_length=3, r1_pcrel=0, r1_symbolnum=37), (r2_address=238, r2_type=0, r2_extern=1, r2_length=3, r2_pcrel=0, r2_symbolnum=30)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)

--  While building simple Setup.hs using:
      /Users/<______>/.stack/programs/x86_64-osx/ghc-8.4.3/bin/ghc-8.4.3 -rtsopts -threaded -clear-package-db -global-package-db -hide-all-packages -package base -main-is StackSetupShim.mainOverride -package Cabal-2.2.0.1 /Users/<_____>/.stack/setup-exe-src/setup-mPHDZzAJ.hs /Users/<_____>/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -o /Users/<______>/.stack/setup-exe-cache/x86_64-osx/tmp-Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3
    Process exited with code: ExitFailure 1
```

Here's version information that might be of some use:
`clang --version`                                                                                                                                      2022ms  Thu Sep 12 13:59:33 2019
clang version 8.0.1 (tags/RELEASE_801/final)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin

`gcc --version`                                                                                                                                                  143ms  Thu Sep 12 14:03:19 2019
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

`stack --version`                                                                                                                                            Thu Sep 12 14:03:26 2019
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2

`cabal --version`                                                                                                                                                       Thu Sep 12 14:03:31 2019
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library

`xcodebuild --version`
Xcode 10.2.1
Build version 10E1001

Any idea what could be going on here? I'm brand new to Exercism and just got things set up, so I'm probably missing something stupid - just let me know!

**Comment by petertseng** [comment]
I found https://docs.haskellstack.org/en/stable/faq/#how-do-i-resolve-linker-errors-when-running-stack-setup-or-stack-build-on-macos about this. Might be worth a try.

**Comment by Datamance** [comment]
> The error message suggests to me that you're using GHC 8.4.3.
> 
> I think you should try and install GHC 8.6.5 instead.
> 
> And I think you should try and do it via the Stack tool by first installing it:
> 
> https://docs.haskellstack.org/en/stable/install_and_upgrade/#macos
> 
> Let me know how you progress.

Fairly certain I'm using 8.6.5 -
```
<_________>  ~/E/h/hello-world  ghc --version                                                                                                                                                            Sun Sep 15 13:28:58 2019
The Glorious Glasgow Haskell Compilation System, version 8.6.5
```
- but also not entirely sure because I still don't really understand how GHC versions are "containerized" per project (I come from the python/JS world, so I'm used to package management stuff a la virtualenv/pip for Python and npm for JS). This could just be my global version I guess? It would seem that way from the output of `which`:

```
<_________>  ~/E/h/hello-world  which ghc                                                                                                                                                                Mon Sep 16 10:37:21 2019
/Users/ricorodriguez/.ghcup/bin/ghc
```

**Comment by Datamance** [comment]
> I found https://docs.haskellstack.org/en/stable/faq/#how-do-i-resolve-linker-errors-when-running-stack-setup-or-stack-build-on-macos about this. Might be worth a try.

Interesting - I did indeed have `/usr/local/opt/llvm/bin` in my PATH - just removed it, and am getting a slightly different error:

```
 ricorodriguez  ~/E/h/hello-world  stack build                                                                                                                          Mon Sep 16 11:08:11 2019
Linking /Users/ricorodriguez/.stack/setup-exe-cache/x86_64-osx/tmp-Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3 ...
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
clang: error: invalid linker name in argument '-fuse-ld=lld'
`gcc' failed in phase `Linker'. (Exit code: 1)

--  While building simple Setup.hs using:
      /Users/ricorodriguez/.stack/programs/x86_64-osx/ghc-8.4.3/bin/ghc-8.4.3 -rtsopts -threaded -clear-package-db -global-package-db -hide-all-packages -package base -main-is StackSetupShim.mainOverride -package Cabal-2.2.0.1 /Users/ricorodriguez/.stack/setup-exe-src/setup-mPHDZzAJ.hs /Users/ricorodriguez/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -o /Users/ricorodriguez/.stack/setup-exe-cache/x86_64-osx/tmp-Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3
```

Also @sshine sorry I didn't read more closely before - now seeing that stack really is invoking the wrong ghc executable somehow. I'm going to dig a bit deeper to try and understand why that's happening (probably an artifact of having tried to install all the Haskell-stack stuff earlier and then trying again recently with this Exercism stuff)

**Comment by Datamance** [comment]
what's strange too is that I get this Linker failure even using `stack [build|test] --system-ghc`, and even after updating `~/.stack/config.yaml` with `system-ghc: true`.

since there is no config clause dealing with ghc version in `hello-world's` `stack.yaml` (that file literally just has `resolver: lts-12.4` in it), one would assume that stack would use my system GHC based on the user-set flags that I have in `~/.stack/config.yaml`. But it doesn't. It keeps using 8.4.3.

I will keep hacking at this after work, but in the meantime I'd appreciate any pointers.

**Comment by Datamance** [comment]
OK, I seemed to have fixed things but am perplexed as to why:

1) I ran `stack --resolver lts-14.6 test` - which I would assume changes the resolver/snapshot for _that specific test build that I just invoked_, *not* a permanent change (which I would expect to be reflected in the local `stack.yaml`)
2) The test build works! 
3) local `stack.yaml`, as expected, still reads `resolver: lts-12.4`. So I will expect a `stack test` (with no other flags passed) to fail.
4) Run `stack test`. The test runs perfectly fine. *_WTF_*.

What changed under the hood, and why?

**Comment by NobbZ** [comment]
You now have artifacts in your cache, which won't get rebuild, I assume. IIRC correctly, there should be a `.stack` folder in the project, if you remove that, then you'll be back to "normal" fails ;)

**Comment by sshine** [comment]
@NobbZ: Perhaps you mean `.stack-work/`?

And thanks for providing an explanation, I wouldn't have had a good guess. :-)

> I still don't really understand how GHC versions are "containerized" per project (I come from the python/JS world, so I'm used to package management stuff a la virtualenv/pip for Python and npm for JS).

Package managers are much alike. Two things Stack does different from virtualenv/pip and npm is that it also keeps track of your GHC, and it keeps track of different packages and GHCs by keeping them in `~/.stack`, that is, in your homedir.

So if you have three Stack projects where two use GHC 8.6.5 and one uses GHC 8.4.4, it makes sure that you only waste space for two instances of the compiler and that your project directory isn't flooded with copies of packages, which, for example, is the case with virtualenv/pip and npm.

> This could just be my global version I guess?

Stack *can* use the "system GHC" if you call it with e.g.

    $ stack ghc --system-ghc -- --version
    The Glorious Glasgow Haskell Compilation System, version 8.6.5

*(The syntax is a little confusing here, but essentially, `stack ghc` is the sub-command, `--system-ghc` is an argument for `stack ghc`, and `--` is necessary to separate the arguments from `stack ghc` and `ghc` itself, with `--version` being an argument to `ghc`. So this command would print the version of whatever Stack thinks is the "system GHC".)*

"System GHC" *could* be a copy of GHC residing in `/usr`. But it could also be a copy of GHC that Stack installed into `~/.stack`. Those are not "system GHCs" in the sense of being installed in `/usr`. So, for example, on my system, if I type

    $ which ghc
    $

I get no result: What Stack regards as a system GHC in my case is actually buried deep inside `~/.stack` under names like `.stack/programs/x86_64-linux/ghc-8.4.4/bin/ghc` because I installed it via Stack.

Maybe you have a `ghc` binary in your `$PATH`, and this one is broken? It's not necessary to have them in my `$PATH` because I call them via `stack ghc` which knows where to look. And if I understand @NobbZ'es comment right, doing `stack ... --resolver=14.6` will download a functioning GHC and use that instead of the system GHC.

If I do

    $ find ~/.stack -name ghc -exec {} --version \; | sort -u
    The Glorious Glasgow Haskell Compilation System, version 8.0.1
    The Glorious Glasgow Haskell Compilation System, version 8.0.2
    The Glorious Glasgow Haskell Compilation System, version 8.2.2
    The Glorious Glasgow Haskell Compilation System, version 8.4.3
    The Glorious Glasgow Haskell Compilation System, version 8.4.4
    The Glorious Glasgow Haskell Compilation System, version 8.6.3
    The Glorious Glasgow Haskell Compilation System, version 8.6.4
    The Glorious Glasgow Haskell Compilation System, version 8.6.5

you can see that I should probably be cleaning this up, since I hardly use them all any more.

Having the notion of a system GHC, even though it's managed by Stack in `~/.stack`, is particularly useful if you want to run GHC outside of a project directory, but not make Stack begin to compete for control over `/usr` with my operating system's package manager. For example, if I want a GHCi unburdened by any particular project's dependencies, I can hit `stack ghci` in my homedir (8.6.5 by default in my case), and I get access to the accumulation of all packages I installed for all projects compatible with the resolver that picks GHC 8.6.5.

So if you end up in a trap like this again, I *think* you can do any of the following:
 - You can `rm -rf ~/.stack ~/.ghc ~/.cabal` to get rid of all GHCs and packages you have cached.
 - You can `brew uninstall haskell-platform` (if this is how you got started)
 - You can install `brew install haskell-stack`
 - You can `stack install ghc --resolver=14.6`

I'm closing this issue for now, but feel free to respond.
