### ISSUE TITLE
Bump canonical exercise versions

### ISSUE THREAD

**Issue by sshine** [exercism/haskell#852]
Most exercises on the Haskell track have unit tests that are based on *canonical tests* shared between all Exercism tracks in [exercism/problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises). When alterations are made to these tests, the unit tests that mirror them on the Haskell track come out of sync.

The task at hand is to pick an exercise where versions have come out of sync and make the necessary changes to the Haskell test suite for that exercise. A list of exercises for which this is relevant can be generated by the following site: https://tracks.exercism.io/haskell/master (updates automatically) or using e.g. [`up-to-date/hs.rb`](https://github.com/petertseng/exercism-problem-specifications/tree/up-to-date/up-to-date).

Protocol: To avoid race conditions, you can declare that you intend to bump a specific exercise here before submitting a PR. One PR per version bump per exercise. Most exercises are only one version bump behind.

An extract from #849 made Oct 1, 2019, **updated Oct 17**:

- [ ] palindrome-products: 1.1.0.4 < 1.2.0
- [x] forth: 1.7.0.11 < 1.7.1
- [x] pangram: 1.4.1.11 < 2.0.0
- [ ] phone-number: 1.6.1.8 < 1.7.0
- [x] clock: 2.3.0.8 < 2.4.0
- [x] space-age: 1.1.0.5 < 1.2.0
- [x] robot-simulator: 3.1.0.7 < 3.2.0
- [ ] luhn: 1.3.0.6 < 1.6.1
- [ ] anagram: 1.4.0.8 < 1.5.0
- [ ] queen-attack: 2.2.0.7 < 2.3.0
- [x] acronym: 1.6.0.10 < 1.7.0
- [ ] allergies: 1.2.0.7 < 2.0.0
- [x] matrix: 1.1.0.7 < 1.3.0
- [ ] simple-cipher: 1.2.0.5 < 2.0.0
- [x] word-count: 1.3.0.7 < 1.4.0
- [x] armstrong-numbers: 1.0.0.2 < 1.1.0
- [x] leap: 1.5.1.9 < 1.6.0
- [x] etl: 1.0.0.5 < 2.0.1
- [ ] ~~beer-song~~
- [ ] ~~food-chain~~
- [ ] ~~house~~
- [ ] ~~triangle~~

For example PRs of such version bumps, see [all PRs labelled `sync/tests`](https://github.com/exercism/haskell/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3Async%2Ftests+).

A quick checklist:
- Find [the latest canonical tests for a given exercise](https://github.com/exercism/problem-specifications/tree/master/exercises).
- Make sure that the version in package.yaml is bumped according to [this track's versioning policy](https://github.com/exercism/haskell#exercise-versioning): Same as the canonical test version + a 4th incremental serial component.
- Make sure to reference, in the commit message, the PR(s) in exercism/problem-specifications that address the canonical version bump(s): `exercism/problem-specifications#XYZ`. See e.g. #817 for an example of this.

Happy Hacktoberfest!

**Comment by SleeplessByte** [comment]
(Please update the link to https://tracks.exercism.io/haskell/master ; the old one will no longer be updated 📦 )

**Comment by karen-pal** [comment]
Hello, I'm going to have a go at the armstrong's number one!

**Comment by karen-pal** [comment]
Also working on the leap one!

**Comment by karen-pal** [comment]
Working on word count.

**Comment by thalesmg** [comment]
Hello, I'll work on ETL!

**Comment by barrymoo** [comment]
I will try `pangram`

**Comment by thalesmg** [comment]
It's not on the PR's description list, but it is on https://tracks.exercism.io/haskell/master : can I take `beer-song`?

**Comment by petertseng** [comment]
there are are a few exercises that are not in the list, and the reasons are documented in https://github.com/petertseng/exercism-problem-specifications/blob/ea8b66b0799c786bf6848aced02b5bf02d017883/up-to-date/hs.rb#L4-L8, which I will reproduce here for convenience:

```
  'beer-song' => 'refactoring exercise in Haskell, tests entire song only',
  'food-chain' => 'refactoring exercise in Haskell, tests entire song only',
  'house' => 'refactoring exercise in Haskell, tests entire song only',

  'triangle' => 'currently divergent and staying with data, as of https://github.com/exercism/xhaskell/pull/484',
```

Since they deliberately diverge from problem-specifications, getting them back in line will likely be more work than the other exercises. So I'd recommend trying the other exercises. Or you could take a look at beer-song and we could have a discussion on whether it should stay divergent or get back in line. Since the decision was made so long ago and in different circumstances, maybe circumstances have changed such that the time is right to reverse the decision.

**Comment by petertseng** [comment]
EBWODP: updating link to https://github.com/petertseng/exercism-problem-specifications/blob/up-to-date/up-to-date/hs.rb#L4-L8

**Comment by thalesmg** [comment]
Thanks for the explanation, @petertseng !

I'll work on `robot-simulator` then. =)

**Comment by sshine** [comment]
I'm closing this issue as it relates to last year's Hacktoberfest.
