### ISSUE TITLE
resistor-color-duo and property tests

### ISSUE THREAD

**Issue by sshine** [exercism/haskell#867]
After #865, resistor-color-duo's `value :: (Color, Color) -> Int` is ideal for property testing.

Some properties that can be tested:

- `value (Black, x) < 10` for all `x`
- `value (x, y) >= 10` for all `x` except `Black` and all `y`
- `show (value (x, y)) == reverse (show (value (y, x)))` for all `x`, `y` except `Black`.
- `(Color, Color)` is isomorphic to `[0..99]` (or: all colors have a unique value).
- Associativity: Kind of tricky because you can't get the value of a single Color:
  ```
  value (k, x) <= value (k, y) && value (k, y) <= value (k, z)
    ⇒ value (k, x) <= value (k, z)

  value (x, k) <= value (y, k) && value (y, k) <= value (z, k)
    ⇒ value (k, x) <= value (k, z)
  ```

Considering how simple this exercise is, adding all these property tests with the purpose to aid students is slightly overkill. (It could use a few more unit tests for basic coverage, though.)

So I thought: Why not encourage property testing in `.meta/hints.md`?

In the style of #843, add one or two property tests and encourage others.

A pull request that proposes this awaits for #865 to merge.

**Comment by barrymoo** [comment]
> So I thought: Why not encourage property testing in .meta/hints.md?

Basically, you want to show the student how to write a `QuickCheck` property test and then suggest a few properties to test? (with links to documentation etc?)

**Comment by sshine** [comment]
Yes, that was my thought.

**Comment by sshine** [comment]
@barrymoo: If you'd like, #865 has now been merged and this issue is ready to be worked on.

**Comment by barrymoo** [comment]
@sshine I was going to work on this today, but I noticed the `Hints` section is no longer displayed on the exercism website? Cases where we have implemented the `Data.Text` library aren't mentioned.

**Comment by sshine** [comment]
@barrymoo: Thank you for noticing!

@iHiD: Can you explain why #865, which was merged a month ago, which adds a hint to the README *and* updates test/Tests.hs, does not get updated on the website? Is this a bug, or is there a precondition that I'm not aware of?

**Comment by iHiD** [comment]
Hello. It's there for me when I go to the track anew and check. Maybe you're versions of the exercise are out of date? Do you see the button to click to update it?

<img width="1006" alt="Screenshot 2019-12-10 at 11 38 52" src="https://user-images.githubusercontent.com/286476/70490427-aac3bc00-1b41-11ea-90b7-3b7bca0bd52f.png">

**Comment by barrymoo** [comment]
@iHiD Updating worked for me. I am hoping to work on this soon!
