### ISSUE TITLE
Recruiting additional maintainers for Haskell

### ISSUE THREAD

**Issue by kytrinyx** [exercism/haskell#887]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by sshine** [comment]
Existing maintainer, I'll have 2-3 hours.

I've so far refrained from beginning because I believe some groundwork exists. For example, one could build a richer set of exercises around the curriculum structure of Brent Yorgey's [CIS 194](https://www.seas.upenn.edu/~cis194/spring13/lectures.html) course, which is also recommended in [Learn Haskell](https://github.com/bitemyapp/learnhaskell/blob/master/README.md).

**Comment by petertseng** [comment]
Existing maintainer who is unsure of consistently having 2-3 hours. I will help out where I can.

**Comment by aimorris** [comment]
Hi, my name is Adam Morris. I am wishing to help maintain the Haskell track and push it towards v3, as I believe it is a fundamental language to learn. I am pretty crap at Haskell itself, but I can help out as much as possible.

https://exercism.io/Adam-Morris

**Comment by sshine** [comment]
I am closing this issue now.

@aimorris: Would you still like to be a maintainer for the Haskell track?
