### ISSUE TITLE
crypto-square: tests do not actually verify whitespace

### ISSUE THREAD

**Issue by nicuveo** [exercism/haskell#895]
The problem statement explains that text should be justified, and the [canonical tests](https://github.com/exercism/problem-specifications/blob/master/exercises/crypto-square/canonical-data.json) do seem to suggest that we should verify that (some "expected" strings have trailing whitespace).

However, we currently do not compare the strings: we do several tests to provide very detailed error messages... but we ignore all those whitespace issues in the process of doing so.

I would be fairly easy to fix: just one additional test that checks that the two strings are identical. But I chose to open an issue rather than just create a PR, to discuss how to best approach this.

**Comment by sshine** [comment]
While non-core exercises (the ones that are often associated with a low chance of immediate or any feedback, and which I've proposed that we're able to disable feedback for in exercism/exercism#5153) don't receive a lot of attention, you are quite right.

You are welcome to submit an additional test. It would probably be a worthy addition to the canonical tests also, even though they are still locked down. So let's put a pin in that for now.

**Comment by sshine** [comment]
At this point, the problem-specifications repository [has been re-opened](https://github.com/exercism/problem-specifications/issues/1686).

Before then it was always an option to just add a test in this repository only.

Would you be interested in doing either at this point, @nicuveo?

**Comment by petertseng** [comment]
I see that the decision to ignore whitespace was a deliberate decision, with the reasoning in https://github.com/exercism/haskell/issues/259. However, my judgment will be that as long as our output is a String, it's better to keep it as the problem description says, for it would be against the description if a student emitted an output with a lot of leading spaces (among others). If we change the output to a [String], then we could freely choose whether to require the trailing spaces or forbid them.

**Comment by petertseng** [comment]
I considered changing this in https://github.com/exercism/problem-specifications/pull/1827, but my main observation is that since this is a ciphering exercise, the focus isn't on human understandability of the output.
