### ISSUE TITLE
Stack test don't run (No setup information found for ghc-8.8.3 on your platform)

### ISSUE THREAD

**Issue by zbioe** [exercism/haskell#913]
I'm trying to get stack up and running in hello example, but when i try to run `stack test` it returns next error:
```
$ stack test
No setup information found for ghc-8.8.3 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'linux64-ncurses6'.
Supported versions: ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2
```
please, can you help with this issue? sorry any inconvenience. Thank's

Stack version:
```
/home/jimf/exercism/haskell/hello-world jimf@YoMoY[1]
$ stack --version
Version 2.3.1, Git revision de2a7b694f07de7e6cf17f8c92338c16286b2878 (8103 commits) x86_64 hpack-0.33.0
```

Os INFO (Void Linux):
```
$ uname -srvmo
Linux 5.4.41_1 #1 SMP PREEMPT Thu May 14 17:43:28 UTC 2020 x86_64 GNU/Linux
```

**Comment by sshine** [comment]
Hi @zbio,

I googled "No setup information found for ghc-8.8.3 on your platform." and found the following thread:

Going a little down the result list, there is literally an FAQ entry in the Stack documentation:

https://docs.haskellstack.org/en/stable/faq/#how-do-i-install-ghc-in-stack-when-it-fails-with-the-error-missing-ghc-bindist-for-linux64-ncurses6

I'm going to close this issue, but feel free to respond with whether you succeeded or not. :)
