### ISSUE TITLE
Stack test failed (linked hspec discover) Catalina 10.15.5

### ISSUE THREAD

**Issue by Hakimba** [exercism/haskell#914]
I got this error on every exercisms when i execute "stack test"

ghc version : 8.8.3
stack = 2.3.1

> hspec-discover> Building executable 'hspec-discover' for hspec-discover-2.7.1..

> hspec-discover> [1 of 2] Compiling Main

> hspec-discover> [2 of 2] Compiling Paths_hspec_discover

> hspec-discover> Linking .stack-work/dist/x86_64-osx/Cabal-3.0.1.0/build/hspec-discover/hspec-discover ...

> hspec-discover> Undefined symbols for architecture x86_64:

> hspec-discover>   "___darwin_check_fd_set_overflow", referenced from:

> hspec-discover>       _awaitEvent in libHSrts.a(Select.o)

> hspec-discover> ld: symbol(s) not found for architecture x86_64

> hspec-discover> clang: error: linker command failed with exit code 1 (use -v to see invocation)

> hspec-discover> `clang' failed in phase `Linker'. (Exit code: 1)

**Comment by tejasbubane** [comment]
Quick search resulted in these: https://github.com/haskell/haskell-ide-engine/issues/1058 and https://github.com/haskell/haskell-ide-engine/issues/1791 Might help.

**Comment by sshine** [comment]
Hi @Hakimba. Have you experienced any progress on this issue?

Since it dates back to June, I am going to close it for now, but feel free to get back in case you still have compilation problems.
