### ISSUE TITLE
[v3] Add tags

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/haskell#939]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

In Exercism v3, tracks can be annotated with tags. This allows searching for tracks with a certain tag combination, making it easy for students to find an interesting track to join.

Tags are specified in the top-level `"tags"` field in the track's `config.json` file and are defined as an array of strings, as specified in [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/tracks/config-json.md#tags).

## Goal

The `"tags"` field in the `config.json` file should be updated to contain the tags that are relevant to this track. The list of tags that can be used is listed in [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/tracks/config-json.md#tags).

## Example

```json
{
  "tags": [
    "runtime/jvm",
    "platform/windows",
    "platform/linux",
    "paradigm/declarative",
    "paradigm/functional",
    "paradigm/object_oriented"
  ]
}
```

## Tracking

https://github.com/exercism/v3-launch/issues/1

**Comment by SleeplessByte** [comment]
This was incorrectly closed as https://github.com/exercism/haskell/pull/981 mentioned this issue should have remained to define the tasks.

**Comment by SleeplessByte** [comment]
If someone picks this up, you can use [a TAGS.md document](https://github.com/exercism/javascript/blob/main/TAGS.md) to advocate why certain tags should be applied.

**Comment by MatthijsBlom** [comment]
@gacallea Will you picking this up?

In any case, here is the [documentation on tags](https://exercism.org/docs/building/tracks/config-json#h-tags).

**Comment by gacallea** [comment]
@MatthijsBlom I can definitely give it a go tomorrow after work. cheers!

**Comment by MatthijsBlom** [comment]
I just adapted the `TAGS.md` linked above to Haskell. I'll post it to your PR when it appears, for comparison.

**Comment by gacallea** [comment]
I'm giving it a go here: https://github.com/gacallea/haskell/blob/main/config.json#L1322-L1330 -- PR in a sec :)
